---
name: CI Build with tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 21 ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - uses: actions/setup-java@v4
        id: test_jdk
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: set build_jdk
        env:
          JAVA_HOME: ${{ steps.build_jdk.outputs.path }}
        run: |
          echo "$JAVA_HOME/bin" >> ${GITHUB_PATH}

      - name: build distribution
        env:
          JAVA_HOME: ${{ steps.build_jdk.outputs.path }}
          MAVEN_ARGS: "-Dbasepom.check.skip-enforcer=false -B -fae"
        run: |
          make install-notests

      - name: set test_jdk
        env:
          JAVA_HOME: ${{ steps.test_jdk.outputs.path }}
        run: |
          echo "$JAVA_HOME/bin" >> ${GITHUB_PATH}

      - name: run tests
        env:
          JAVA_HOME: ${{ steps.test_jdk.outputs.path }}
          MAVEN_ARGS: "-B -fae"
        run: |
          make run-tests
